name: Nuget publish to NuGet gallery@DmitryLegostaev
author: DmitryLegostaev
description: Simple build, pack and publish .nupkg file to NuGet gallery

inputs:
  PROJECT_NAME: 
    description: Project name
    required: true
  DOTNET_CONFIGURATION:
    description: Configuration name for .NET project
    required: false
    default: "Release"
  NUGET_API_KEY:
    description: Key to use with nuget push
    required: true
  NUGET_URL:
    description: NuGet url.
    required: false
    default: "https://api.nuget.org/v3/index.json"
  DOTNET_VERSION:
    description: .NET version to use
    required: false
    default: "6.0.x"

runs: 
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.DOTNET_VERSION }}

    - name: Restore dependencies
      shell: bash
      run: dotnet restore "${{ inputs.PROJECT_NAME }}"

    - name: Build
      shell: bash
      run: dotnet build "${{ inputs.PROJECT_NAME }}" --no-restore --configuration ${{ inputs.DOTNET_CONFIGURATION }}

    - name: Nuget pack project
      shell: bash
      run: dotnet pack --no-build "${{ inputs.PROJECT_NAME }}" --configuration ${{ inputs.DOTNET_CONFIGURATION }} --output .

    - name: Nuget publish
      shell: bash
      run: dotnet nuget push ${{ inputs.PROJECT_NAME }}*.nupkg --api-key ${{ inputs.NUGET_API_KEY }} --source ${{ inputs.NUGET_URL }}
